---
- name: Nettverk versjon switcher
  hosts: switcher
  connection: network_cli
  gather_facts: no

   
  tasks:
    - name: Hent versjon fra switcher
      ios_command:
        commands: show version
      register: output

    - name: Skriv ut versjon
      debug:
        var: output

    